name: Checkov

on:
  pull_request:
    paths:
      - 'k8s-manifests/**'
      - '**/*.yaml'
      - '**/*.yml'
    branches:
      - main

concurrency:
  group: checkov-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  checkov-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Run Checkov Scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: k8s-manifests/mysql
          framework: kubernetes
